# Generated by Django 2.2.12 on 2020-10-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoursessoclient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssorecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='ssorecord',
            name='external_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
